### ISSUE TITLE
KafkaQueueAdapter Task.Run

### ISSUE THREAD

**Issue by danielmarbach** [gigya/Orleans.KafkaStreamProvider#15]
kafkaQueueAdapter uses Task.Run to execute async API on KafkaNet. Can you explain why? Usually you should not use Task.Run/Factory.StartNew for async IO

**Comment by gabikliot** [comment]
Already asked that here: https://github.com/dotnet/orleans/issues/1205#issuecomment-167055355
and it was answered there.
The reason is basically the same as you issue https://github.com/gigya/Orleans.KafkaStreamProvider/issues/16.

**Comment by randa1** [comment]
Closing this as the discussion is ongoing in #16
